### ISSUE TITLE
学Javascript, 没有遇到问题吗?

### ISSUE THREAD

**Issue by gutenye** [642495539/learn-feng#1]
原来JavaScript这么简单呀.

```javascript
document.querySelector("button").addEventListener("click", e => {
  console.log("You just clicked a button")
})
```

这个看的懂的吧.

**Comment by 642495539** [comment]
在像当初学c语言一样研究javascript,
想弄明白javascript的对象模型，感觉难点是this,prototype etc,

repository中的文件怎么删除？

**Comment by 642495539** [comment]
pull request是什么意思

**Comment by gutenye** [comment]
> repository中的文件怎么删除？

```
$ rm -r a.txt
$ git commit -a -m 'delete'
$ git push
```

**Comment by 642495539** [comment]
这些命令放哪里运行

**Comment by gutenye** [comment]
这些是linux命令. Windows自己转换一下, 都能懂的. 比如`rm a.txt`是remove删除文件的意思.
Windows下用资源管理器就好了.
`git push` 是把代码发到Github上面, 你原来在Windows下怎么做就怎么做.

On Sun, Jan 31, 2016 at 9:04 PM, 642495539 <notifications@github.com> wrote:

> 这些命令放哪里运行
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/642495539/learn-feng/issues/1#issuecomment-177496614>.
>



-- 
Linux, Vim, Ruby, Go and Javascript
- Guten.me  <http://GutenYe.com>
- GitHub.com/GutenYe <http://Github.com/GutenYe>

**Comment by gutenye** [comment]
先关了, 有问题自己再新建一个Issue
